# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- repeater
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_12_x:
      node_version: 12.x
steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
- script: |
    npm install
    npm install @neuraLegion/nexploit-cli -g || true
    SCAN_ID=$(nexploit-cli repeater qdbdlpc.nexp.wlwaucimb4ilwzpjdijz9y0we5uyw3u5 --token --id sVAwKV5EHkEPCgbGCp13C2)
    echo $SCAN_ID