trigger:
- repeater
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_12_x:
      node_version: 12.x
steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
- script: |
    npm install
    npm install @NeuraLegion/nexploit-cli -g || true
      echo "Start Repeater :checkered_flag:"
      PID_REPEATER=$(nexploit-cli repeater --token 2kwsuht.nexa.x2k2k0089qnkxlajuzyhmhnc4knfbm3r --id pQVpFx4swaytVDV9m5p3fS &> /dev/null & echo $!)
      echo "Repeater started PID: $PID_REPEATER\n"
      sleep 10
      echo "Start NeuraLegion Scan :checkered_flag:"
      SCAN_ID=$(nexploit-cli scan:run --token 2kwsuht.nexa.x2k2k0089qnkxlajuzyhmhnc4knfbm3r --repeater pQVpFx4swaytVDV9m5p3fS --name "Azure scan with repeater" --crawler https://brokencrystals.com/ --smart)
      echo "Scan was started with ID https://app.neuralegion.com/scans/$SCAN_ID\n"
      sleep 10
      echo "Wait for issues :hourglass_flowing_sand:\n"
      RESULT=$(nexploit-cli scan:polling --interval 30s --timeout 20m --token 2kwsuht.nexa.x2k2k0089qnkxlajuzyhmhnc4knfbm3r --breakpoint medium_issue $SCAN_ID)
      if [ -z "$RESULT" ]
      then
          echo "Failed to stop scan"
      else
          echo "Stop Scan :octagonal_sign:"
          nexploit-cli scan:stop --token 2kwsuht.nexa.x2k2k0089qnkxlajuzyhmhnc4knfbm3r $SCAN_ID
      fi